### ISSUE TITLE
http://registry.jsonresume.org/ is down

### ISSUE THREAD

**Issue by VaibhavP17** [jsonresume/registry-server#104]
Hi,

I have been using jsonresume for quite some time now and I just enjoy it. 

But unfortunately, the **http://registry.jsonresume.org/** is down for couple of weeks now and I need to update my resume. Can you please help me with this ? I need to apply to some of the jobs.

**Comment by aodj** [comment]
Any movement on this?

**Comment by jorgeas80** [comment]
I just downloaded the code, exported this variable

`export REGISTRY_SERVER=http://localhost:5000`

And then followed the instructions. I have a local server running. So, I can register a new user. But it still throws an 522 error when trying to access

http://localhost:5000/myuser

Working on it

**Comment by thomasdavis** [comment]
So mainly we need a way to execute npm packages (themes) against a POST'ed resume.json.

In the past I use to run a server (theme-server) that pulled down jsonresume-theme-* packages and ran them against resume.jsons. It was too hard to manage. I'm wondering if there is a way we can do it serverless.

I will be deploying a new serverless theme server within the hour, all themes will need to be manually added to the project to deploy.

As for the registry, I am trying to figure out some nice instructions to self host instead of publishing to a shared database.

**Comment by thomasdavis** [comment]
If anyone would like a backup of their old resume, let me know. I also started an email campaign to send off old resume.jsons.

**Comment by thomasdavis** [comment]
https://github.com/jsonresume/registry-server/issues/105
