### ISSUE TITLE
registry crashes on failed validation

### ISSUE THREAD

**Issue by JonathanMH** [jsonresume/registry-server#76]
My validation errors cause it to output the .json I guess, could someone look at this?

http://registry.jsonresume.org/a58a3c79

**Comment by thomasdavis** [comment]
It's actually because the latest version of that theme is broken.

e.g. http://registry.jsonresume.org/a58a3c79?theme=kendall will work.

I've already alerted the theme developer.

Luckily, we can also use older versions of themes with JSON Resume

Such as http://registry.jsonresume.org/a58a3c79?theme=elegant@0.9.11

When setting your theme using the cli just add `@0.9.11`

**Comment by JonathanMH** [comment]
Oh, ok, thank you!

On 10 October 2015 09:18:01 CEST, Thomas Davis <notifications@github.com> wrote:
>It's actually because the latest version of that theme is broken.
>
>e.g. http://registry.jsonresume.org/a58a3c79?theme=kendall will work.
>
>I've already alerted the theme developer.
>
>Luckily, we can also use older versions of themes with JSON Resume
>
>Such as http://registry.jsonresume.org/a58a3c79?theme=elegant@0.9.11
>
>When setting your theme using the cli just add `@0.9.11`
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/jsonresume/registry-server/issues/76#issuecomment-147048422

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mudassir0909** [comment]
This issue is now fixed, visit http://registry.jsonresume.org/a58a3c79
